// Homepage copy only. Loaded after i18n.js so dashboard copy remains unchanged.
import { DICT } from './i18n.js';

const LANDING_COPY = {
  ko: {
    'meta.title': 'CNOL RADAR · 오늘 뭐 올리지? 내 채널에 맞는 답.',
    'meta.description': '내 채널과 레퍼런스의 공개 데이터를 한곳에서 살펴보세요. 참고할 쇼츠, 수집 추세, 브리핑, 소재 보드로 다음 영상의 아이디어를 정리하는 CNOL RADAR.',
    'meta.ogTitle': '오늘 뭐 올리지? 내 채널에 맞는 답. · CNOL RADAR',
    'meta.ogDescription': '참고할 영상부터 다음 소재까지, 매일의 쇼츠 리서치를 한곳에. 공개 데이터로 무료 체험하세요.',
    'nav.features': '할 수 있는 일',
    'nav.how': '이용 방법',
    'nav.pricing': '출시 예정 요금',
    'nav.faq': '자주 묻는 질문',
    'nav.login': '체험 화면',
    'nav.start': '무료로 체험하기',
    'hero.over': '내 채널의 다음 소재를 찾는 CNOL RADAR',
    'hero.h1a': '오늘 뭐 올리지?',
    'hero.h1b': '내 채널에 맞는 답.',
    'hero.sub': '내 채널과 레퍼런스를 함께 살펴, 참고할 영상과 다음 소재를 한곳에 정리하세요. 매일의 리서치가 가벼워집니다.',
    'hero.cta1': '무료로 소재 찾아보기',
    'hero.cta2': '크롬 확장 · 준비 중',
    'hero.cta2b': '어떤 화면인지 보기',
    'hero.note': '공개 데이터 체험 · 공용 실험 공간 · 개인 채널 연결 준비 중',
    'hero.b1': '수납 아이디어',
    'hero.b2': '반려동물 소재',
    'hero.b3': '여행 레퍼런스',
    'hero.b4': '편의점 리뷰',
    'hero.f1t': '주목할 레퍼런스 · 예시',
    'hero.f1d': '자취요리 1분 · 공개 조회수 변화',
    'hero.f2t': '수집 추세 · 48시간 예시',
    'hero.f2v': '128만 회 · 예시',
    'demo.note': '화면과 수치는 서비스 흐름을 설명하는 예시입니다.',
    'st.1v': '소재 발견',
    'st.1t': '다음 영상의 시작점',
    'st.2v': '레퍼런스 비교',
    'st.2t': '한곳에서 보는 채널 변화',
    'st.3v': '브리핑',
    'st.3t': '앱에서 확인하는 오늘의 흐름',
    'st.4v': '제작 보드',
    'st.4t': '아이디어에서 업로드까지',
    'mc.over': '내 채널과 레퍼런스',
    'mc.h2': '여기저기 찾던 영상,\n한곳에 모아보세요.',
    'mc.sub': '운영하는 채널과 참고할 채널의 공개 데이터를 나란히 살펴보세요. 조회수 변화와 업로드 흐름을 비교하며 다음 소재의 실마리를 찾습니다.',
    'mc.b1': '공개 조회수로 살펴보는 48시간 수집 추세',
    'mc.b2': '채널별 흐름과 합산 흐름을 한 화면에서',
    'mc.b3': '레퍼런스의 새 영상과 조회수 변화 확인',
    'mc.b4': '업로드 주기와 영상 유형을 나란히 비교',
    'mc.chart': '등록 채널 합산 · 48시간 예시',
    'mc.hub': '공개 데이터 수집',
    'mc.up': '변화 +23% · 예시',
    'mc.aria': '예시 채널과 레퍼런스의 공개 데이터를 한곳에 모아 48시간 수집 추세로 비교하는 화면',
    'dash.over': '대시보드 미리 보기',
    'dash.h2': '숫자를 보고,\n다음 소재를 고르는 화면.',
    'dash.sub': '수집한 채널의 변화, 참고할 쇼츠, 브리핑과 소재 보드를 함께 볼 수 있습니다. 아래 화면은 예시이며, 현재 체험은 공개 데이터를 사용하는 공용 공간입니다.',
    'dash.open': '공용 체험 화면 열기',
    'dash.aria': '예시 데이터로 구성한 CNOL RADAR 대시보드',
    'dash.brandSub': '공용 실험 모드',
    'dash.sample': '화면·수치 예시',
    'dash.title': '오늘의 리서치',
    'dash.homeSub2': '등록 채널 5개를 비교하는 예시 · 실제 내 채널 데이터가 아닙니다',
    'dash.m1': '대시보드',
    'dash.m2': '소재 찾기',
    'dash.m3': '업로드 패턴',
    'dash.m4': '참고할 쇼츠',
    'dash.m5': '이슈 모니터링',
    'dash.m6': '채널 추가',
    'dash.m7': '채널 목록',
    'dash.m8': '소재 보드',
    'dash.s1': '오늘 살펴볼 것',
    'dash.s2': '레퍼런스',
    'dash.s3': '제작',
    'dash.mine': '운영 채널 · 예시',
    'dash.ref': '레퍼런스 · 예시',
    'dash.live': '공개 조회수 수집 추세 · 48시간',
    'dash.live2': '48시간 수집 추세 · 예시',
    'dash.daily': '일별 수집 추세 · 28일',
    'dash.daily2': '일별 수집 추세 · 예시',
    'dash.rankNote': '공개 조회수의 수집 시점별 차이를 살펴보는 자체 추세입니다. YouTube Studio의 공식 실시간 수치와 다릅니다.',
    'dash.confirmed': '공개 조회수 변화로 계산한 추세 · 수집 기록이 있는 기간만 표시',
    'dash.tryT': '다음 영상, 이렇게 시도해볼까요?',
    'dash.trySub': '공개 데이터의 패턴을 참고한 실험 제안 예시 · 결과를 보장하지 않습니다',
    'dash.tyHi': '표본 참고',
    'dash.tyMid': '추가 확인',
    'dash.tyFit': '참고 점수 {n} · 예시',
    'dash.ty3l': '자취요리 1분 · 조회수 비교 예시 · 참고 점수 93',
    'dash.ytBand': '비교 범위 · 예시',
    'how.over': '이용 방법',
    'how.h2': '채널을 모으고, 소재를 고르고, 제작으로.',
    'how.sub': '공개 채널 링크로 리서치 흐름을 먼저 체험하세요. 개인 계정 연결과 사용자별 공간은 준비 중입니다.',
    'how.s1t': '참고할 채널 추가',
    'how.s1d': '유튜브 채널 주소나 @핸들, 쇼츠 링크로 공개 채널을 추가합니다. 현재는 누구나 함께 사용하는 공용 실험 공간입니다.',
    'how.s2t': '변화와 영상 살펴보기',
    'how.s2d': '수집한 공개 조회수의 변화와 업로드 패턴을 비교하세요. 키워드로 새로운 레퍼런스도 찾아볼 수 있습니다.',
    'how.s3t': '다음 소재를 보드에 담기',
    'how.s3d': '참고할 영상을 고르고 소재 보드에 정리하세요. 앱 안의 브리핑과 이슈 목록으로 채널 변화를 다시 확인할 수 있습니다.',
    'bt.over': '할 수 있는 일',
    'bt.h2': '찾는 시간은 줄이고,\n만들 소재는 선명하게.',
    'bt.sub': '채널 추가부터 레퍼런스 탐색, 소재 정리까지. 지금은 공개 데이터로 리서치 흐름을 체험할 수 있습니다.',
    'bt.try.t': '다음 영상의 실험 아이디어',
    'bt.try.d': '수집한 쇼츠의 시간·길이·제목 유형을 참고해 시도할 방향을 살펴보세요. 패턴은 참고 자료이며 성과의 원인이나 결과를 확정하지 않습니다.',
    'bt.pick.t': '내 채널 기준으로 소재 찾기',
    'bt.pick.d': '등록한 채널과 레퍼런스의 분야·키워드·영상 길이를 비교하며 참고할 소재를 고릅니다. 비공개 채널 데이터 연동과 AI 고도화는 준비 중입니다.',
    'bt.agent.t': '앱 안에서 보는 브리핑',
    'bt.agent.d': '수집 흐름과 이슈 목록을 앱 안에서 함께 확인하세요. 개인별 브리핑과 메일·메신저 알림은 준비 중입니다.',
    'bt.algo.t': '업로드 패턴 살펴보기',
    'bt.algo.d': '시간대·요일·길이·제목 유형별로 공개 성과를 비교합니다. 함께 나타난 패턴을 살펴보는 기능이며 알고리즘의 원인을 해독하는 기능은 아닙니다.',
    'bt.curve.t': '영상의 변화 살펴보기',
    'bt.curve.d': '수집 기록이 쌓인 영상의 조회수 변화와 같은 채널의 영상을 비교하세요. 데이터가 부족한 기간은 추세를 확인하기 어렵습니다.',
    'bt.find.t': '새 레퍼런스 탐색',
    'bt.find.d': '키워드로 관련 쇼츠와 채널을 찾아 리서치 범위를 넓히세요. 마음에 드는 채널은 레퍼런스로 추가할 수 있습니다.',
    'bt.cmp.t': '채널을 나란히 비교',
    'bt.cmp.d': '업로드 주기와 공개 조회수의 변화를 같은 화면에서 비교합니다. 비슷한 분야에서도 서로 다른 흐름을 살펴보세요.',
    'bt.board.t': '아이디어를 제작으로',
    'bt.board.d': '참고한 영상과 소재를 보드에 담고 아이디어 → 대본 → 업로드로 정리하세요. 현재 체험 보드는 공용 공간입니다.',
    'bt.m.prof': '채널 기준 · 예시',
    'bt.m.fit1': '참고 점수 93 · 예시',
    'bt.m.fit2': '참고 점수 81 · 예시',
    'bt.m.n1': '레퍼런스의 조회수 변화',
    'bt.m.n1s': '자취요리 1분 · 비교 예시',
    'bt.m.n2': '업로드 간격 확인',
    'bt.m.n2s': '냥집사 일기 · 3일 공백 예시',
    'bt.m.n3': '앱 안의 브리핑',
    'bt.m.n3s': '수집 흐름 · 참고할 소재 예시',
    'bt.m.hit': '평소 대비 증가 비율',
    'bt.try.n1': '쇼츠 9개 비교 · 예시',
    'bt.try.n2': '쇼츠 14개 비교 · 예시',
    'bt.try.n3': '참고 점수·조회수 비교 예시',
    'why.over': 'CNOL RADAR가 그리는 흐름',
    'why.h2': '소재 발견에서 제작까지.\n그다음은 협업으로.',
    'why.sub': '매일 흩어지는 리서치를 제작으로 이어지는 한 흐름에 모읍니다. 음원과 광고 협업은 다음 단계로 준비하고 있습니다.',
    'why.c1t': '근거를 함께 보는 소재',
    'why.c1d': '참고 영상과 공개 데이터의 변화를 함께 살펴, 제작할 소재의 실마리를 찾습니다.',
    'why.c2t': '제작으로 이어지는 보드',
    'why.c2d': '찾아둔 아이디어를 대본과 업로드 단계로 정리해 다음 작업을 이어갑니다.',
    'why.c3t': '음원 협업 · 준비 중',
    'why.c3d': '채널에 맞는 음원과 협업 기회를 연결할 계획입니다. 이용 범위와 권리·정산 조건은 협업마다 확인해야 합니다.',
    'why.c4t': '광고·PPL 연결 · 준비 중',
    'why.c4d': '채널과 브랜드의 협업 기회를 연결할 계획입니다. 캠페인 성사나 수익을 보장하지 않습니다.',
    'why.th1': '혼자 리서치할 때',
    'why.r1': '채널 탐색',
    'why.r1a': '채널마다 화면을 오가며 확인',
    'why.r1b': '등록한 채널을 한 화면에서 비교',
    'why.r2': '변화 확인',
    'why.r2a': '조회수를 그때마다 따로 기록',
    'why.r2b': '수집한 공개 조회수 변화 살펴보기',
    'why.r3': '소재 정리',
    'why.r3a': '링크와 메모가 여기저기 흩어짐',
    'why.r3b': '참고 영상과 소재를 보드에 정리',
    'why.r4': '다음 작업',
    'why.r4a': '저장한 소재를 다시 찾아 정리',
    'why.r4b': '아이디어 → 대본 → 업로드 단계로 관리',
    'price.over': '출시 예정 요금',
    'price.h2': '정식 출시 예정 요금',
    'price.sub': '지금은 공개 데이터를 사용하는 무료 공용 체험입니다. 아래 유료 혜택은 출시 계획이며 현재 결제는 제공하지 않습니다.',
    'price.krw': '원화',
    'price.usd': '달러',
    'price.month': '월 요금',
    'price.year': '연 요금 · 검토 중',
    'price.perMonth': '월 요금 · 출시 예정',
    'price.perYear': '연 요금 {x} · 출시 예정',
    'price.noCard': '공용 실험 모드',
    'price.note': '원화는 부가세 포함 예정 가격입니다. 가격·혜택·사용 한도는 정식 출시 시 확정하며 현재 결제는 없습니다.',
    'plan.free': '무료 체험',
    'plan.solo': '크리에이터',
    'plan.team': '팀',
    'plan.rec': '출시 계획',
    'plan.public': '공개 채널 체험',
    'plan.freeWho': '공개 채널 체험',
    'plan.ch1': '내 채널 1개 · 출시 예정',
    'plan.ch5': '내 채널 최대 5개 · 출시 예정',
    'plan.f1': '공개 채널 등록',
    'plan.f2': '레퍼런스 탐색·비교',
    'plan.f3': '공용 소재 보드',
    'plan.s1': '내 채널 데이터 기반 맞춤 추천',
    'plan.s2': '일별·월별 성과 분석',
    'plan.s3': '개인 브리핑과 이슈 알림',
    'plan.s4': '개인 레퍼런스 목록·소재 보드',
    'plan.t1': '크리에이터의 모든 기능',
    'plan.t2': '내 채널 최대 5개 관리',
    'plan.t3': '팀원 3명과 소재 보드 공유',
    'plan.t4': '채널 비교와 팀 브리핑',
    'plan.preview': '무료 체험 화면 보기',
    'plan.start': '무료 체험 화면 보기',
    'faq.h2': '시작 전에 궁금한 것',
    'faq.q1': '지금 채널은 어떻게 등록하나요?',
    'faq.a1': '채널 링크나 @핸들로 공개 채널을 등록해 체험할 수 있습니다. 현재는 다른 이용자와 함께 쓰는 공용 공간으로 누구나 등록 목록을 보고 변경할 수 있으며, 개인 계정 연결과 사용자별 분리는 준비 중입니다.',
    'faq.q2': '에이전트는 지금 무엇을 해주나요?',
    'faq.a2': '공개 데이터를 수집하고 앱 안에서 추세·소재 제안·브리핑·이슈 목록을 보여줍니다. 비공개 채널 데이터 기반 AI 개인화와 메일·메신저로 보내는 개인 알림은 준비 중입니다.',
    'faq.q3': '48시간 수치는 YouTube Studio와 같은가요?',
    'faq.a3': '공개 조회수를 수집한 시점별 차이로 계산한 자체 추세이므로 YouTube Studio의 공식 실시간 수치와 다릅니다. 수집 간격과 누락에 영향을 받으며, 화면 예시는 실제 채널 성과가 아닙니다.',
    'faq.q4': '채널 데이터를 회사의 공통 데이터로 쓰나요?',
    'faq.a4': '현재 체험은 공개 데이터를 사용하는 공용 공간입니다. 향후 권한이 필요한 채널 연결은 수집 범위·목적·보관·삭제를 안내하고 동의된 사용자별 서비스에 한해 쓰도록 설계할 예정이며, 비공개 데이터를 회사의 공통 자산으로 무조건 가져오는 방식으로 운영하지 않습니다.',
    'faq.q5': '음원이나 광고 협업도 바로 연결되나요?',
    'faq.a5': '음원·광고·PPL 연동은 준비 중입니다. 협업이 제공되더라도 권리와 이용 범위, 계약·정산 조건을 개별 확인해야 하며 성사나 수익을 보장하지 않습니다.',
    'faq.q6': '크롬 확장은 사용할 수 있나요?',
    'faq.a6': '크롬 확장은 준비 중입니다. 선택한 영상의 링크를 레퍼런스로 저장하는 흐름을 계획하고 있으며, 출시 전 필요한 권한과 수집 범위를 안내할 예정입니다.',
    'faq.q7': '참고한 원본 영상을 그대로 써도 되나요?',
    'faq.a7': '레퍼런스 저장은 링크와 소재를 정리하는 기능이며 영상 저장·다운로드나 이용 허락을 제공하지 않습니다. 원본·음원 사용에는 권리자 허락이나 적용 가능한 이용 권한을 확인해야 합니다.',
    'ask.h3': '필요한 기능을 들려주세요.',
    'ask.p': '채널 운영 중 막히는 일이나 궁금한 점을 남겨주세요.',
    'ask.email': '답변 받을 이메일',
    'ask.msg': '궁금한 점·필요한 기능',
    'ask.send': '문의 남기기',
    'ask.ok': '문의가 접수되었습니다. 남겨주신 내용을 확인하겠습니다.',
    'ask.fail': '문의가 접수되지 않았습니다. 잠시 후 다시 시도해주세요.',
    'cta2.h2': '다음 영상의 시작점,\n지금 찾아보세요.',
    'cta2.sub': '공개 채널과 레퍼런스로 소재 탐색을 무료 체험하세요. 현재는 함께 사용하는 공용 실험 공간입니다.',
    'foot.co': '에이치알컴퍼니 주식회사',
    'foot.contact': '문의',
    'foot.terms': '이용약관',
    'foot.privacy': '개인정보처리방침',
    'foot.api': 'CNOL RADAR는 YouTube API 서비스를 사용합니다. 48시간 수집 추세는 YouTube Studio의 공식 실시간 수치와 다릅니다.',
    'foot.ytToS': 'YouTube 서비스 약관',
    'foot.gPriv': 'Google 개인정보처리방침'
  },
  en: {
    'meta.title': 'CNOL RADAR · Your next video idea',
    'meta.description': 'Explore public data from your channel and references in one place. CNOL RADAR helps organize your next video idea with reference Shorts, collected trends, briefings and an idea board.',
    'meta.ogTitle': 'What should I post today? An answer for your channel. · CNOL RADAR',
    'meta.ogDescription': 'Keep reference videos and your next ideas together. Try your daily Shorts research with public data for free.',
    'nav.features': 'What you can do',
    'nav.how': 'How it works',
    'nav.pricing': 'Planned pricing',
    'nav.faq': 'FAQ',
    'nav.login': 'Trial dashboard',
    'nav.start': 'Try for free',
    'hero.over': 'CNOL RADAR finds your channel’s next idea',
    'hero.h1a': 'What should I post today?',
    'hero.h1b': 'An answer for your channel.',
    'hero.sub': 'Explore your channel and references together. Keep videos worth studying and your next ideas in one place, making daily research easier.',
    'hero.cta1': 'Find ideas for free',
    'hero.cta2': 'Chrome extension · in development',
    'hero.cta2b': 'Preview the dashboard',
    'hero.note': 'Public-data trial · Shared experimental space · Private channel connection in development',
    'hero.b1': 'Storage ideas',
    'hero.b2': 'Pet topics',
    'hero.b3': 'Travel references',
    'hero.b4': 'Snack reviews',
    'hero.f1t': 'A reference to explore · example',
    'hero.f1d': '1-Min Cooking · public view changes',
    'hero.f2t': 'Collected trend · 48h example',
    'hero.f2v': '1.28M views · example',
    'demo.note': 'The screens and figures are examples that illustrate the service workflow.',
    'st.1v': 'Find ideas',
    'st.1t': 'A starting point for your next video',
    'st.2v': 'Compare references',
    'st.2t': 'Channel changes in one place',
    'st.3v': 'Briefings',
    'st.3t': 'Today’s trends inside the app',
    'st.4v': 'Production board',
    'st.4t': 'From idea to upload',
    'mc.over': 'Your channel and references',
    'mc.h2': 'Keep the videos you research\ntogether in one place.',
    'mc.sub': 'Review public data from the channels you run and the channels you study side by side. Compare view changes and upload patterns to find a starting point for your next idea.',
    'mc.b1': '48-hour collected trends from public view counts',
    'mc.b2': 'Per-channel trends and combined trends in one view',
    'mc.b3': 'New reference videos and changes in views',
    'mc.b4': 'Upload schedules and video types compared side by side',
    'mc.chart': 'Registered channels combined · 48h example',
    'mc.hub': 'Public-data collection',
    'mc.up': 'Change +23% · example',
    'mc.aria': 'Example public data from channels and references brought together to compare 48-hour collected trends',
    'dash.over': 'Dashboard preview',
    'dash.h2': 'Review the numbers.\nChoose your next idea.',
    'dash.sub': 'See channel changes, reference Shorts, briefings and an idea board together. This preview uses examples; the current trial is a shared space using public data.',
    'dash.open': 'Open the shared trial',
    'dash.aria': 'CNOL RADAR dashboard with example data',
    'dash.brandSub': 'Shared experimental mode',
    'dash.sample': 'Example screens and figures',
    'dash.title': 'Today’s research',
    'dash.homeSub2': 'Example comparison of 5 registered channels · not your actual channel data',
    'dash.m1': 'Dashboard',
    'dash.m2': 'Find ideas',
    'dash.m3': 'Upload patterns',
    'dash.m4': 'Reference Shorts',
    'dash.m5': 'Issue monitoring',
    'dash.m6': 'Add channels',
    'dash.m7': 'Channel list',
    'dash.m8': 'Idea board',
    'dash.s1': 'Today’s research',
    'dash.s2': 'References',
    'dash.s3': 'Production',
    'dash.mine': 'Managed channel · example',
    'dash.ref': 'Reference · example',
    'dash.live': 'Collected public-view trend · 48h',
    'dash.live2': '48h collected trend · example',
    'dash.daily': 'Daily collected trend · 28 days',
    'dash.daily2': 'Daily collected trend · example',
    'dash.rankNote': 'Our trend uses differences between collected public view counts. It differs from YouTube Studio’s official real-time figures.',
    'dash.confirmed': 'Trend calculated from public-view changes · only periods with collection records',
    'dash.tryT': 'A direction to try for your next video',
    'dash.trySub': 'Example experiments informed by public-data patterns · results are not guaranteed',
    'dash.tyHi': 'Sample reference',
    'dash.tyMid': 'Review further',
    'dash.tyFit': 'Reference score {n} · example',
    'dash.ty3l': '1-Min Cooking · example view comparison · reference score 93',
    'dash.ytBand': 'Comparison range · example',
    'how.over': 'How it works',
    'how.h2': 'Collect channels. Choose ideas. Start creating.',
    'how.sub': 'Try the research workflow with public channel links. Private account connection and separate user spaces are in development.',
    'how.s1t': 'Add channels to study',
    'how.s1d': 'Add public channels with a YouTube channel URL, @handle or Shorts link. The current experimental space is shared by all users.',
    'how.s2t': 'Explore videos and changes',
    'how.s2d': 'Compare collected changes in public views and upload patterns. Use keywords to discover more references.',
    'how.s3t': 'Save your next idea to the board',
    'how.s3d': 'Choose reference videos and organize ideas on the board. Revisit channel changes through in-app briefings and issue lists.',
    'bt.over': 'What you can do',
    'bt.h2': 'Less searching.\nA clearer idea of what to make.',
    'bt.sub': 'Add channels, explore references and organize ideas. You can currently try this research workflow with public data.',
    'bt.try.t': 'Experiments for your next video',
    'bt.try.d': 'Explore directions to try using collected Shorts’ timing, length and title types. Patterns are references; they do not establish causes or guarantee results.',
    'bt.pick.t': 'Find ideas with your channel in mind',
    'bt.pick.d': 'Compare topics, keywords and video lengths from registered channels and references to choose ideas. Personalization using private channel data and advanced AI is in development.',
    'bt.agent.t': 'Briefings inside the app',
    'bt.agent.d': 'Review collected trends and issue lists together in the app. Personal briefings and email or messenger notifications are in development.',
    'bt.algo.t': 'Explore upload patterns',
    'bt.algo.d': 'Compare public performance by time, day, length and title type. This explores patterns that occur together; it does not decode the algorithm’s causes.',
    'bt.curve.t': 'Explore changes in a video',
    'bt.curve.d': 'Compare recorded changes in views with other videos from the same channel. Trends are difficult to assess where collection records are insufficient.',
    'bt.find.t': 'Discover new references',
    'bt.find.d': 'Find related Shorts and channels by keyword to expand your research. Add channels you want to study as references.',
    'bt.cmp.t': 'Compare channels side by side',
    'bt.cmp.d': 'Compare upload schedules and changes in public views on one screen. Explore how channels in similar topics can follow different patterns.',
    'bt.board.t': 'Move ideas toward production',
    'bt.board.d': 'Save reference videos and topics to a board, then organize them from idea to script to upload. The current trial board is shared.',
    'bt.m.prof': 'Channel criteria · example',
    'bt.m.fit1': 'Reference score 93 · example',
    'bt.m.fit2': 'Reference score 81 · example',
    'bt.m.n1': 'Reference video view changes',
    'bt.m.n1s': '1-Min Cooking · comparison example',
    'bt.m.n2': 'Check upload intervals',
    'bt.m.n2s': 'Cat Diary · 3-day gap example',
    'bt.m.n3': 'In-app briefing',
    'bt.m.n3s': 'Collected trends · idea examples',
    'bt.m.hit': 'Share above usual views',
    'bt.try.n1': '9 Shorts compared · example',
    'bt.try.n2': '14 Shorts compared · example',
    'bt.try.n3': 'Reference score and view comparison example',
    'why.over': 'The CNOL RADAR workflow',
    'why.h2': 'From discovering ideas to creating.\nThen toward collaboration.',
    'why.sub': 'Bring scattered daily research into a workflow that leads to production. Music and brand collaboration are being prepared as the next step.',
    'why.c1t': 'Ideas with references to review',
    'why.c1d': 'Explore reference videos alongside public-data changes to find a starting point for what to create.',
    'why.c2t': 'A board that leads to production',
    'why.c2d': 'Organize saved ideas into script and upload stages so you can continue your next task.',
    'why.c3t': 'Music collaboration · in development',
    'why.c3d': 'We plan to connect channels with suitable music and collaboration opportunities. Usage rights and payment terms must be checked for each collaboration.',
    'why.c4t': 'Brand deals and PPL · in development',
    'why.c4d': 'We plan to connect channels and brands with collaboration opportunities. Campaigns and revenue are not guaranteed.',
    'why.th1': 'Researching on your own',
    'why.r1': 'Explore channels',
    'why.r1a': 'Move between separate channel pages',
    'why.r1b': 'Compare registered channels in one view',
    'why.r2': 'Review changes',
    'why.r2a': 'Record view counts separately each time',
    'why.r2b': 'Explore changes in collected public views',
    'why.r3': 'Organize ideas',
    'why.r3a': 'Links and notes scattered across tools',
    'why.r3b': 'Keep references and ideas on a board',
    'why.r4': 'The next task',
    'why.r4a': 'Find and organize saved ideas again',
    'why.r4b': 'Manage stages from idea to script to upload',
    'price.over': 'Planned launch pricing',
    'price.h2': 'Planned pricing for launch',
    'price.sub': 'The current public-data trial is free and shared. Paid features below are planned for launch; payments are not currently available.',
    'price.krw': 'KRW',
    'price.usd': 'USD',
    'price.month': 'Monthly price',
    'price.year': 'Annual pricing · under review',
    'price.perMonth': 'Monthly price · planned for launch',
    'price.perYear': 'Annual price {x} · planned for launch',
    'price.noCard': 'Shared experimental mode',
    'price.note': 'Planned KRW prices include VAT. Prices, features and usage limits will be finalized at launch; payments are not currently available.',
    'plan.free': 'Free trial',
    'plan.solo': 'Creator',
    'plan.team': 'Team',
    'plan.rec': 'Launch plan',
    'plan.public': 'Public-channel trial',
    'plan.freeWho': 'Public-channel trial',
    'plan.ch1': '1 managed channel · planned for launch',
    'plan.ch5': 'Up to 5 managed channels · planned for launch',
    'plan.f1': 'Add public channels',
    'plan.f2': 'Explore and compare references',
    'plan.f3': 'Shared idea board',
    'plan.s1': 'recommendations from your channel data',
    'plan.s2': 'daily and monthly performance analysis',
    'plan.s3': 'personal briefings and issue notifications',
    'plan.s4': 'personal references and idea board',
    'plan.t1': 'all Creator features',
    'plan.t2': 'manage up to 5 channels',
    'plan.t3': '3 team members sharing an idea board',
    'plan.t4': 'channel comparison and team briefings',
    'plan.preview': 'View the free trial',
    'plan.start': 'View the free trial',
    'faq.h2': 'Before you start',
    'faq.q1': 'How do I add a channel now?',
    'faq.a1': 'Try adding a public channel with its link or @handle. This is currently a shared space where anyone can view and change registered channels. Private account connection and separate user spaces are in development.',
    'faq.q2': 'What does the agent currently do?',
    'faq.a2': 'It collects public data and shows trends, idea suggestions, briefings and issue lists inside the app. AI personalization using private channel data and personal email or messenger notifications are in development.',
    'faq.q3': 'Are the 48-hour figures the same as YouTube Studio?',
    'faq.a3': 'They are our own trend calculated from differences between collected public view counts, so they differ from YouTube Studio’s official real-time figures. Collection intervals and missing records affect them; preview examples are not actual channel performance.',
    'faq.q4': 'Will channel data become shared company data?',
    'faq.a4': 'The current trial is a shared space using public data. Future authorized channel connections are planned to explain collection scope, purpose, retention and deletion, with data limited to the user-specific service covered by consent. Private data will not be automatically taken as a common company asset.',
    'faq.q5': 'Can I access music or brand collaborations now?',
    'faq.a5': 'Music, brand-deal and PPL integrations are in development. If offered, rights, usage scope, contracts and payment terms must be reviewed individually. Collaborations and revenue are not guaranteed.',
    'faq.q6': 'Is the Chrome extension available?',
    'faq.a6': 'The Chrome extension is in development. We plan a workflow for saving selected video links as references, with required permissions and collection scope explained before launch.',
    'faq.q7': 'Can I use a reference video as it is?',
    'faq.a7': 'Saving a reference organizes links and ideas; it does not store or download videos or grant usage permission. Check the rights holder’s permission or other applicable usage rights before using original footage or music.',
    'ask.h3': 'Tell us what you need.',
    'ask.p': 'Share a channel-management question or a task you find difficult.',
    'ask.email': 'Email for a reply',
    'ask.msg': 'Your question or feature request',
    'ask.send': 'Send inquiry',
    'ask.ok': 'Your inquiry was received. We will review what you shared.',
    'ask.fail': 'Your inquiry was not received. Please try again shortly.',
    'cta2.h2': 'Find a starting point\nfor your next video.',
    'cta2.sub': 'Try idea research with public channels and references for free. The current experimental space is shared.',
    'foot.co': 'HR Company Co., Ltd.',
    'foot.contact': 'Contact',
    'foot.terms': 'Terms',
    'foot.privacy': 'Privacy Policy',
    'foot.api': 'CNOL RADAR uses YouTube API Services. Its 48-hour collected trends differ from YouTube Studio’s official real-time figures.',
    'foot.ytToS': 'YouTube Terms of Service',
    'foot.gPriv': 'Google Privacy Policy'
  },
  ja: {
    'meta.title': 'CNOL RADAR · あなたのチャンネルの次のネタ',
    'meta.description': '自分のチャンネルとリファレンスの公開データを1か所で確認。参考になるショート、収集した推移、ブリーフィング、ネタボードで次の動画のアイデアを整理するCNOL RADARです。',
    'meta.ogTitle': '今日は何を投稿しよう？ チャンネルに合う答えを。 · CNOL RADAR',
    'meta.ogDescription': '参考動画から次のネタまで、毎日のショート動画リサーチを1か所に。公開データで無料体験できます。',
    'nav.features': 'できること',
    'nav.how': '使い方',
    'nav.pricing': '公開予定の料金',
    'nav.faq': 'よくある質問',
    'nav.login': '体験画面',
    'nav.start': '無料で体験する',
    'hero.over': 'チャンネルの次のネタを探す CNOL RADAR',
    'hero.h1a': '今日は何を投稿しよう？',
    'hero.h1b': 'チャンネルに合う答えを。',
    'hero.sub': '自分のチャンネルとリファレンスを一緒に確認し、参考動画と次のネタを1か所に整理しましょう。毎日のリサーチが軽くなります。',
    'hero.cta1': '無料でネタを探す',
    'hero.cta2': 'Chrome拡張 · 準備中',
    'hero.cta2b': '画面を見てみる',
    'hero.note': '公開データで体験 · 共有の実験スペース · 個人チャンネル連携は準備中',
    'hero.b1': '収納アイデア',
    'hero.b2': 'ペットのネタ',
    'hero.b3': '旅行のリファレンス',
    'hero.b4': 'コンビニレビュー',
    'hero.f1t': '注目するリファレンス · 表示例',
    'hero.f1d': '1分自炊 · 公開再生数の変化',
    'hero.f2t': '収集した推移 · 48時間の例',
    'hero.f2v': '128万回 · 表示例',
    'demo.note': '画面と数値は、サービスの流れを説明するための例です。',
    'st.1v': 'ネタ発見',
    'st.1t': '次の動画の出発点',
    'st.2v': 'リファレンス比較',
    'st.2t': 'チャンネルの変化を1か所に',
    'st.3v': 'ブリーフィング',
    'st.3t': 'アプリで確認する今日の動き',
    'st.4v': '制作ボード',
    'st.4t': 'アイデアから投稿まで',
    'mc.over': '自分のチャンネルとリファレンス',
    'mc.h2': '探していた動画を、\n1か所に集めましょう。',
    'mc.sub': '運営するチャンネルと参考にするチャンネルの公開データを並べて確認します。再生数の変化と投稿の傾向を比較し、次のネタの手がかりを探しましょう。',
    'mc.b1': '公開再生数から見る48時間の収集推移',
    'mc.b2': 'チャンネル別の動きと合計を1画面に',
    'mc.b3': 'リファレンスの新着動画と再生数の変化を確認',
    'mc.b4': '投稿ペースと動画のタイプを並べて比較',
    'mc.chart': '登録チャンネルの合計 · 48時間の例',
    'mc.hub': '公開データを収集',
    'mc.up': '変化 +23% · 表示例',
    'mc.aria': '例示チャンネルとリファレンスの公開データを1か所に集め、48時間の収集推移を比較する画面',
    'dash.over': 'ダッシュボードを見てみる',
    'dash.h2': '数字を見て、\n次のネタを選ぶ画面。',
    'dash.sub': 'チャンネルの変化、参考ショート、ブリーフィング、ネタボードを一緒に確認できます。下の画面は表示例です。現在の体験版は公開データを使う共有スペースです。',
    'dash.open': '共有の体験画面を開く',
    'dash.aria': '例示データで構成したCNOL RADARのダッシュボード',
    'dash.brandSub': '共有の実験モード',
    'dash.sample': '画面・数値の表示例',
    'dash.title': '今日のリサーチ',
    'dash.homeSub2': '登録チャンネル5件を比較する例 · 実際のマイチャンネルのデータではありません',
    'dash.m1': 'ダッシュボード',
    'dash.m2': 'ネタ探し',
    'dash.m3': '投稿パターン',
    'dash.m4': '参考ショート',
    'dash.m5': '問題のモニタリング',
    'dash.m6': 'チャンネル追加',
    'dash.m7': 'チャンネル一覧',
    'dash.m8': 'ネタボード',
    'dash.s1': '今日見ること',
    'dash.s2': 'リファレンス',
    'dash.s3': '制作',
    'dash.mine': '運営チャンネル · 表示例',
    'dash.ref': 'リファレンス · 表示例',
    'dash.live': '公開再生数の収集推移 · 48時間',
    'dash.live2': '48時間の収集推移 · 表示例',
    'dash.daily': '日別の収集推移 · 28日間',
    'dash.daily2': '日別の収集推移 · 表示例',
    'dash.rankNote': '収集時点ごとの公開再生数の差から見る独自の推移です。YouTube Studioの公式リアルタイム数値とは異なります。',
    'dash.confirmed': '公開再生数の変化から計算した推移 · 収集記録のある期間のみ表示',
    'dash.tryT': '次の動画、こう試してみませんか？',
    'dash.trySub': '公開データのパターンを参考にした実験の提案例 · 成果を保証するものではありません',
    'dash.tyHi': '表示例 · 標本を参考に',
    'dash.tyMid': '表示例 · 追加確認',
    'dash.tyFit': '参考スコア {n} · 表示例',
    'dash.ty3l': '1分自炊 · 再生数の比較例 · 参考スコア93',
    'dash.ytBand': '比較範囲 · 表示例',
    'how.over': '使い方',
    'how.h2': 'チャンネルを集め、ネタを選び、制作へ。',
    'how.sub': '公開チャンネルのリンクでリサーチの流れを体験してください。個人アカウント連携とユーザー別スペースは準備中です。',
    'how.s1t': '参考にするチャンネルを追加',
    'how.s1d': 'YouTubeチャンネルURL、@ハンドル、ショートのリンクで公開チャンネルを追加します。現在は誰でも一緒に使う共有の実験スペースです。',
    'how.s2t': '変化と動画を確認',
    'how.s2d': '収集した公開再生数の変化と投稿パターンを比較します。キーワードで新しいリファレンスも探せます。',
    'how.s3t': '次のネタをボードに保存',
    'how.s3d': '参考動画を選び、ネタボードに整理しましょう。アプリ内のブリーフィングと問題一覧で、チャンネルの変化を再確認できます。',
    'bt.over': 'できること',
    'bt.h2': '探す時間を減らし、\n作るネタを明確に。',
    'bt.sub': 'チャンネル追加からリファレンス探し、ネタの整理まで。現在は公開データでリサーチの流れを体験できます。',
    'bt.try.t': '次の動画で試すアイデア',
    'bt.try.d': '収集したショートの投稿時間・長さ・タイトル型を参考に、試す方向を確認しましょう。パターンは参考資料であり、成果の原因や結果を確定するものではありません。',
    'bt.pick.t': '自分のチャンネルを基準にネタ探し',
    'bt.pick.d': '登録チャンネルとリファレンスの分野・キーワード・動画の長さを比較し、参考にするネタを選びます。非公開チャンネルデータの連携とAIの高度化は準備中です。',
    'bt.agent.t': 'アプリ内で見るブリーフィング',
    'bt.agent.d': '収集した動きと問題一覧をアプリ内で一緒に確認できます。個人別ブリーフィングとメール・メッセンジャー通知は準備中です。',
    'bt.algo.t': '投稿パターンを確認',
    'bt.algo.d': '時間帯・曜日・長さ・タイトル型別に公開実績を比較します。一緒に現れたパターンを見る機能であり、アルゴリズムの原因を解読する機能ではありません。',
    'bt.curve.t': '動画の変化を確認',
    'bt.curve.d': '収集記録がある動画の再生数の変化と、同じチャンネルの動画を比較します。データが不足する期間は推移の確認が難しくなります。',
    'bt.find.t': '新しいリファレンスを探す',
    'bt.find.d': 'キーワードで関連ショートやチャンネルを探し、リサーチ範囲を広げましょう。気になるチャンネルはリファレンスに追加できます。',
    'bt.cmp.t': 'チャンネルを並べて比較',
    'bt.cmp.d': '投稿ペースと公開再生数の変化を同じ画面で比較します。似た分野でも異なる動きを確認しましょう。',
    'bt.board.t': 'アイデアを制作につなげる',
    'bt.board.d': '参考動画とネタをボードに保存し、アイデア → 台本 → 投稿に整理します。現在の体験ボードは共有スペースです。',
    'bt.m.prof': 'チャンネルの基準 · 表示例',
    'bt.m.fit1': '参考スコア93 · 表示例',
    'bt.m.fit2': '参考スコア81 · 表示例',
    'bt.m.n1': 'リファレンスの再生数の変化',
    'bt.m.n1s': '1分自炊 · 比較例',
    'bt.m.n2': '投稿間隔を確認',
    'bt.m.n2s': '猫日記 · 3日間の空白の例',
    'bt.m.n3': 'アプリ内のブリーフィング',
    'bt.m.n3s': '収集した動き · 参考ネタの例',
    'bt.m.hit': '普段を上回った割合',
    'bt.try.n1': 'ショート9本を比較 · 表示例',
    'bt.try.n2': 'ショート14本を比較 · 表示例',
    'bt.try.n3': '参考スコアと再生数の比較例',
    'why.over': 'CNOL RADARが目指す流れ',
    'why.h2': 'ネタ発見から制作まで。\nその先はコラボへ。',
    'why.sub': '毎日散らばるリサーチを、制作につながる1つの流れに集めます。音源と広告のコラボは次の段階として準備中です。',
    'why.c1t': '根拠も一緒に見るネタ',
    'why.c1d': '参考動画と公開データの変化を一緒に確認し、制作するネタの手がかりを探します。',
    'why.c2t': '制作につながるボード',
    'why.c2d': '保存したアイデアを台本と投稿の段階に整理し、次の作業につなげます。',
    'why.c3t': '音源コラボ · 準備中',
    'why.c3d': 'チャンネルに合う音源とコラボの機会をつなぐ計画です。利用範囲、権利、精算条件はコラボごとに確認が必要です。',
    'why.c4t': '広告・PPL連携 · 準備中',
    'why.c4d': 'チャンネルとブランドのコラボ機会をつなぐ計画です。キャンペーンの成立や収益を保証するものではありません。',
    'why.th1': '自分でリサーチする場合',
    'why.r1': 'チャンネル探し',
    'why.r1a': 'チャンネルごとに画面を移動して確認',
    'why.r1b': '登録チャンネルを1画面で比較',
    'why.r2': '変化の確認',
    'why.r2a': '再生数をその都度別々に記録',
    'why.r2b': '収集した公開再生数の変化を確認',
    'why.r3': 'ネタの整理',
    'why.r3a': 'リンクとメモがあちこちに分散',
    'why.r3b': '参考動画とネタをボードに整理',
    'why.r4': '次の作業',
    'why.r4a': '保存したネタを再び探して整理',
    'why.r4b': 'アイデア → 台本 → 投稿の段階で管理',
    'price.over': '公開予定の料金',
    'price.h2': '正式公開時の予定料金',
    'price.sub': '現在は公開データを使う無料の共有体験版です。下の有料機能は正式公開時の計画であり、現在は決済を提供していません。',
    'price.krw': 'ウォン',
    'price.usd': '米ドル',
    'price.month': '月額',
    'price.year': '年額 · 検討中',
    'price.perMonth': '月額 · 正式公開時の予定',
    'price.perYear': '年額{x} · 正式公開時の予定',
    'price.noCard': '共有の実験モード',
    'price.note': 'ウォンは付加価値税込みの予定価格です。価格・機能・利用上限は正式公開時に確定し、現在は決済できません。',
    'plan.free': '無料体験',
    'plan.solo': 'クリエイター',
    'plan.team': 'チーム',
    'plan.rec': '公開時の計画',
    'plan.public': '公開チャンネルで体験',
    'plan.freeWho': '公開チャンネルで体験',
    'plan.ch1': 'マイチャンネル1件 · 正式公開時の予定',
    'plan.ch5': 'マイチャンネル最大5件 · 正式公開時の予定',
    'plan.f1': '公開チャンネルの登録',
    'plan.f2': 'リファレンス探し・比較',
    'plan.f3': '共有ネタボード',
    'plan.s1': '計画 · チャンネルデータに基づく個人向け提案',
    'plan.s2': '計画 · 日別・月別の実績分析',
    'plan.s3': '計画 · 個人別ブリーフィングと問題通知',
    'plan.s4': '計画 · 個人のリファレンス一覧・ネタボード',
    'plan.t1': '計画 · クリエイターの全機能',
    'plan.t2': '計画 · マイチャンネル最大5件の管理',
    'plan.t3': '計画 · メンバー3人でネタボードを共有',
    'plan.t4': '計画 · チャンネル比較とチームのブリーフィング',
    'plan.preview': '無料体験の画面を見る',
    'plan.start': '無料体験の画面を見る',
    'faq.h2': 'はじめる前の疑問',
    'faq.q1': '今はどうやってチャンネルを登録しますか？',
    'faq.a1': 'チャンネルのリンクや@ハンドルで公開チャンネルを登録して体験できます。現在はほかの利用者と使う共有スペースで、誰でも登録一覧を見たり変更したりできます。個人アカウント連携とユーザー別の分離は準備中です。',
    'faq.q2': 'エージェントは今、何をしてくれますか？',
    'faq.a2': '公開データを収集し、アプリ内で推移・ネタの提案・ブリーフィング・問題一覧を表示します。非公開チャンネルデータを使うAI個人化と、メール・メッセンジャーで送る個人通知は準備中です。',
    'faq.q3': '48時間の数値はYouTube Studioと同じですか？',
    'faq.a3': '公開再生数の収集時点ごとの差から計算した独自の推移であり、YouTube Studioの公式リアルタイム数値とは異なります。収集間隔や欠損の影響を受け、画面の表示例は実際のチャンネル実績ではありません。',
    'faq.q4': 'チャンネルデータは会社の共通データになりますか？',
    'faq.a4': '現在の体験版は公開データを使う共有スペースです。今後、権限が必要なチャンネル連携では収集範囲・目的・保管・削除を案内し、同意されたユーザー別サービスに限って使う設計を予定しています。非公開データを無条件に会社の共通資産として取り込む運営はしません。',
    'faq.q5': '音源や広告のコラボはすぐ利用できますか？',
    'faq.a5': '音源・広告・PPL連携は準備中です。提供される場合も、権利、利用範囲、契約・精算条件を個別に確認する必要があります。成立や収益は保証しません。',
    'faq.q6': 'Chrome拡張は使えますか？',
    'faq.a6': 'Chrome拡張は準備中です。選んだ動画のリンクをリファレンスとして保存する流れを計画しており、公開前に必要な権限と収集範囲を案内する予定です。',
    'faq.q7': '参考にした元の動画をそのまま使えますか？',
    'faq.a7': 'リファレンス保存はリンクとネタを整理する機能であり、動画の保存・ダウンロードや利用許諾を提供するものではありません。元の動画や音源を使う際は、権利者の許諾や適用される利用権限を確認してください。',
    'ask.h3': '必要な機能を教えてください。',
    'ask.p': 'チャンネル運営で困っていることや疑問をお寄せください。',
    'ask.email': '返信先のメールアドレス',
    'ask.msg': '疑問・必要な機能',
    'ask.send': '問い合わせる',
    'ask.ok': 'お問い合わせを受け付けました。内容を確認します。',
    'ask.fail': 'お問い合わせを受け付けられませんでした。しばらくしてから再度お試しください。',
    'cta2.h2': '次の動画の出発点を、\n今、探しましょう。',
    'cta2.sub': '公開チャンネルとリファレンスで、ネタ探しを無料体験できます。現在は一緒に使う共有の実験スペースです。',
    'foot.co': 'HR Company株式会社',
    'foot.contact': 'お問い合わせ',
    'foot.terms': '利用規約',
    'foot.privacy': 'プライバシーポリシー',
    'foot.api': 'CNOL RADARはYouTube APIサービスを使用します。48時間の収集推移はYouTube Studioの公式リアルタイム数値とは異なります。',
    'foot.ytToS': 'YouTube利用規約',
    'foot.gPriv': 'Googleプライバシーポリシー'
  }
};

for (const lang of Object.keys(LANDING_COPY)) {
  Object.assign(DICT[lang], LANDING_COPY[lang]);
}
