// Read-only public dashboard. No authentication, database writes or collection actions.
const COPY = {
  ko: { skip:'본문으로 이동',workspace:'크리에이터 리서치',menu:'대시보드 메뉴',overview:'한눈에',references:'레퍼런스',topics:'소재 탐색',public:'공개 데이터',home:'소개 페이지',language:'언어',eyebrow:'대시보드 미리보기 · 공개 데이터',title:'내 다음 영상의 시작.',subtitle:'실제 공개 영상과 채널을 한곳에서 비교해 보세요.',refresh:'다시 불러오기',filters:'영상 필터',groups:'채널 그룹',all:'전체',global:'해외',jp:'일본',company:'운영 채널',search:'영상·채널 검색',sort:'정렬',sortViews:'조회수 높은 순',sortNew:'최신순',summary:'수집 현황',totalViews:'수집 영상 누적 조회수',knownViews:'공개된 영상별 조회수의 합계',videos:'수집 영상',videoNote:'현재 선택한 그룹',channels:'공개 채널',channelNote:'수집 영상이 있는 채널',chart:'채널별 영상 누적 조회수',chartNote:'수집 영상의 공개 조회수를 채널별로 합산했어요.',comparison:'누적 합계 비교',channelList:'참고할 채널',channelListNote:'공개 채널을 살펴보고 실제 영상에서 다음 소재를 찾아보세요.',videoTitle:'지금 살펴볼 영상',topicTitle:'다음 소재를 찾아보세요.',topicSubtitle:'영상 제목과 채널 이름으로 레퍼런스를 검색하세요.',topicVideos:'소재로 참고할 영상',more:'영상 더 보기',footer:'공개 영상 레퍼런스입니다. 다른 채널의 CNOL RADAR 이용 후기나 추천을 의미하지 않습니다.',loading:'공개 영상 데이터를 불러오는 중이에요…',failed:'공개 데이터를 불러오지 못했어요. 다시 불러오기를 눌러 주세요.',empty:'조건에 맞는 영상이 없어요.',unknown:'미확인',viewUnit:'회',items:'개 영상',known:'개 영상의 조회수 확인',videoCount:'개 영상',updated:'자료 확인',thumb:'YouTube 영상',dateUnknown:'게시일 미확인' },
  en: { skip:'Skip to content',workspace:'CREATOR RESEARCH',menu:'Dashboard menu',overview:'Overview',references:'References',topics:'Find ideas',public:'Public data',home:'About CNOL RADAR',language:'Language',eyebrow:'Dashboard preview · Public data',title:'Your next video starts here.',subtitle:'Compare real public videos and channels in one place.',refresh:'Reload data',filters:'Video filters',groups:'Channel groups',all:'All',global:'Global',jp:'Japan',company:'Our channels',search:'Search videos or channels',sort:'Sort',sortViews:'Most viewed',sortNew:'Newest first',summary:'Collection summary',totalViews:'Collected videos · total views',knownViews:'Sum of public view counts for collected videos',videos:'Collected videos',videoNote:'Currently selected group',channels:'Public channels',channelNote:'Channels represented in the collection',chart:'Collected video views by channel',chartNote:'Public video view counts are added up for each channel.',comparison:'Cumulative totals',channelList:'Channels to explore',channelListNote:'Explore public channels and real videos for your next idea.',videoTitle:'Videos to explore',topicTitle:'Find your next idea.',topicSubtitle:'Search reference videos by title or channel name.',topicVideos:'Videos for your next idea',more:'Show more videos',footer:'Public reference videos. These are not testimonials or endorsements of CNOL RADAR by other channels.',loading:'Loading public video data…',failed:'Public data could not be loaded. Select Reload data to try again.',empty:'No videos match these filters.',unknown:'Unverified',viewUnit:'views',items:'videos',known:'videos with verified view counts',videoCount:'videos',updated:'Data checked',thumb:'YouTube video',dateUnknown:'Publication date unavailable' },
  ja: { skip:'本文へ移動',workspace:'クリエイターリサーチ',menu:'ダッシュボードメニュー',overview:'ひと目で',references:'レファレンス',topics:'ネタ探し',public:'公開データ',home:'紹介ページ',language:'言語',eyebrow:'ダッシュボードプレビュー・公開データ',title:'次の動画は、ここから。',subtitle:'実際の公開動画とチャンネルを一か所で比較できます。',refresh:'再読み込み',filters:'動画フィルター',groups:'チャンネルグループ',all:'すべて',global:'海外',jp:'日本',company:'運営チャンネル',search:'動画・チャンネルを検索',sort:'並び順',sortViews:'再生回数が多い順',sortNew:'新しい順',summary:'収集状況',totalViews:'収集動画の累計再生回数',knownViews:'公開された動画別再生回数の合計',videos:'収集動画',videoNote:'現在選択しているグループ',channels:'公開チャンネル',channelNote:'収集動画があるチャンネル',chart:'チャンネル別の動画累計再生回数',chartNote:'収集動画の公開再生回数をチャンネル別に合算しました。',comparison:'累計合計の比較',channelList:'参考にするチャンネル',channelListNote:'公開チャンネルと実際の動画から次のネタを探せます。',videoTitle:'チェックしたい動画',topicTitle:'次のネタを探しましょう。',topicSubtitle:'タイトルやチャンネル名で参考動画を検索できます。',topicVideos:'ネタの参考になる動画',more:'動画をもっと見る',footer:'公開参考動画です。他のチャンネルによるCNOL RADARへの推薦やレビューを意味しません。',loading:'公開動画データを読み込み中です…',failed:'公開データを読み込めませんでした。再読み込みを押してください。',empty:'条件に合う動画はありません。',unknown:'未確認',viewUnit:'回',items:'本の動画',known:'本の再生回数を確認',videoCount:'本の動画',updated:'データ確認',thumb:'YouTube動画',dateUnknown:'公開日未確認' }
};
const $ = (id) => document.getElementById(id);
const state = { lang:'ko',view:'overview',region:'all',search:'',sort:'views',limit:24,videos:[],channels:new Map(),loaded:false,loading:false,error:false,updated:null };
try { const stored=localStorage.getItem('radar.lang'); if(COPY[stored]) state.lang=stored; } catch {}
const text = (key) => (COPY[state.lang] || COPY.ko)[key];
const locale = () => ({ko:'ko-KR',en:'en-US',ja:'ja-JP'})[state.lang];
const num = (value) => value == null ? '—' : Number(value).toLocaleString(locale());
const isCount = (value) => typeof value === 'number' && Number.isFinite(value) && value >= 0;
const normal = (value) => String(value || '').normalize('NFKC').toLowerCase();
const safeImage = (value) => typeof value === 'string' && (value.startsWith('https://') || (value.startsWith('/') && !value.startsWith('//'))) ? value : null;
function node(tag,className,content) { const el=document.createElement(tag); if(className)el.className=className; if(content!=null)el.textContent=content; return el; }
function avatar(channel,size) { const source=safeImage(channel?.thumbnail); if(source){ const img=node('img','preview-avatar');img.src=source;img.alt='';img.loading='lazy';if(size){img.width=size;img.height=size;}return img;}return node('span','preview-avatar preview-avatar-fallback',String(channel?.name||'Y').slice(0,1)); }
function prepare(data) {
  const channels=new Map(); for(const channel of Array.isArray(data.channels)?data.channels:[]){if(channel?.id)channels.set(String(channel.id),{id:String(channel.id),name:String(channel.name||''),thumbnail:channel.thumbnail,region:channel.region});}
  const videos=[], seen=new Set();for(const video of Array.isArray(data.videos)?data.videos:[]){if(!video||!/^[A-Za-z0-9_-]{11}$/.test(video.id||'')||seen.has(video.id))continue;seen.add(video.id);const channelId=String(video.channelId||'');const known=channels.get(channelId);if(!known&&channelId)channels.set(channelId,{id:channelId,name:String(video.channelName||''),thumbnail:null,region:video.region});videos.push({id:video.id,title:String(video.title||''),views:isCount(video.views)?video.views:null,format:video.format==='shorts'?'shorts':'long',channelId,channelName:String(video.channelName||known?.name||''),region:video.region||known?.region||null,thumbnail:video.thumbnail,publishedAt:video.publishedAt||null,company:video.company===true});}
  return {videos,channels};
}
function filtered() { const query=normal(state.search);return state.videos.filter(video=>(state.region==='all'||(state.region==='company'?video.company:video.region===state.region))&&(!query||normal(video.title+' '+video.channelName).includes(query))).sort((a,b)=>state.sort==='new'?(Date.parse(b.publishedAt)||0)-(Date.parse(a.publishedAt)||0):(b.views??-1)-(a.views??-1)); }
function aggregated(videos) { const groups=new Map();for(const video of videos){if(!video.channelId)continue;if(!groups.has(video.channelId))groups.set(video.channelId,{channel:state.channels.get(video.channelId)||{id:video.channelId,name:video.channelName},views:null,count:0});const group=groups.get(video.channelId);group.count++;if(video.views!=null)group.views=(group.views??0)+video.views;}return [...groups.values()].sort((a,b)=>(b.views??-1)-(a.views??-1)); }
function setLabels() {document.documentElement.lang=state.lang;document.title='CNOL RADAR · '+text('overview');document.querySelectorAll('[data-preview-label]').forEach(el=>{el.textContent=text(el.dataset.previewLabel);});document.querySelectorAll('[data-preview-aria]').forEach(el=>el.setAttribute('aria-label',text(el.dataset.previewAria)));document.querySelectorAll('[data-preview-placeholder]').forEach(el=>el.placeholder=text(el.dataset.previewPlaceholder));document.querySelectorAll('[data-preview-lang]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.previewLang===state.lang)));}
function renderChart(groups) {const root=$('previewChart');root.replaceChildren();const known=groups.filter(group=>group.views!=null).slice(0,12);if(!known.length){root.append(node('div','preview-empty',text('empty')));return;}const max=Math.max(...known.map(group=>group.views),1);for(const group of known){const row=node('div','preview-chart-row');const name=node('div','preview-chart-name');name.append(avatar(group.channel),node('span','',group.channel.name));const track=node('div','preview-bar-track');const fill=node('div','preview-bar-fill');fill.style.width=(group.views/max*100)+'%';track.append(fill);row.append(name,track,node('span','preview-chart-value',num(group.views)));root.append(row);} }
function renderChannels(groups) {const root=$('previewChannelGrid');root.replaceChildren();for(const group of groups){const link=node('a','preview-channel-card');if(/^UC[A-Za-z0-9_-]{22}$/.test(group.channel.id)){link.href='https://www.youtube.com/channel/'+group.channel.id;link.target='_blank';link.rel='noopener noreferrer';}const body=node('div');body.append(node('h3','',group.channel.name),node('p','',num(group.count)+' '+text('videoCount')+' · '+num(group.views)+' '+text('viewUnit')));link.append(avatar(group.channel,42),body);root.append(link);}if(!groups.length)root.append(node('div','preview-empty',text('empty')));}
function renderVideos(videos) {const root=$('previewVideoGrid');root.replaceChildren();for(const video of videos.slice(0,state.limit)){const card=node('article','preview-video-card');const link=node('button','preview-thumbnail creator-video');link.type='button';link.dataset.video=video.id;link.dataset.title=video.title;link.dataset.channel=video.channelName;link.dataset.format=video.format;link.setAttribute('aria-label',video.title||text('thumb'));const source=safeImage(video.thumbnail);if(source){const image=node('img');image.src=source;image.alt='';image.loading='lazy';image.width=480;image.height=270;link.append(image);}else link.append(node('span','preview-thumbnail-fallback',text('thumb')));link.append(node('span','preview-play','▶'),node('span','preview-format',video.format==='shorts'?'SHORTS':'VIDEO'));const body=node('div','preview-video-body');body.append(node('h3','',video.title));const author=node('div','preview-video-author');author.append(avatar(state.channels.get(video.channelId)),node('span','',video.channelName));const metadata=node('div','preview-video-meta');const date=Date.parse(video.publishedAt);metadata.append(node('span','preview-video-views',num(video.views)+' '+text('viewUnit')),node('span','',Number.isFinite(date)?new Date(date).toLocaleDateString(locale(),{year:'numeric',month:'short',day:'numeric'}):text('dateUnknown')));body.append(author,metadata);card.append(link,body);root.append(card);}if(!videos.length)root.append(node('div','preview-empty',state.loading?text('loading'):state.error?text('failed'):text('empty')));$('previewMore').hidden=videos.length<=state.limit;$('previewResultCount').textContent=num(videos.length)+' '+text('items');}
function render() {setLabels();const videos=filtered(), groups=aggregated(videos), known=videos.filter(video=>video.views!=null);$('previewTitle').textContent=state.view==='topics'?text('topicTitle'):state.view==='references'?text('channelList'):text('title');$('previewSubtitle').textContent=state.view==='topics'?text('topicSubtitle'):state.view==='references'?text('channelListNote'):text('subtitle');$('previewBreadcrumb').textContent=text(state.view);$('previewVideoTitle').textContent=state.view==='topics'?text('topicVideos'):text('videoTitle');document.querySelectorAll('[data-preview-view]').forEach(el=>{if(el.dataset.previewView===state.view)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current');});document.querySelectorAll('[data-preview-region]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.previewRegion===state.region)));$('previewChartSection').hidden=state.view!=='overview';$('previewChannelsSection').hidden=state.view!=='references';$('previewTotalViews').textContent=known.length?num(known.reduce((sum,video)=>sum+video.views,0)):'—';$('previewVideoCount').textContent=state.loaded?num(videos.length):'—';$('previewChannelCount').textContent=state.loaded?num(groups.length):'—';$('previewViewsNote').textContent=known.length===videos.length?text('knownViews'):num(known.length)+' '+text('known');$('previewRefresh').disabled=state.loading;$('previewStatus').classList.toggle('is-error',state.error);$('previewStatus').textContent=state.loading?text('loading'):state.error?text('failed'):num(state.videos.length)+' '+text('items')+' · '+text('public');$('previewUpdated').textContent=state.updated&&Number.isFinite(Date.parse(state.updated))?text('updated')+' '+new Date(state.updated).toLocaleString(locale(),{dateStyle:'medium',timeStyle:'short'}):'';renderChart(groups);renderChannels(groups);renderVideos(videos);}
async function load() {if(state.loading)return;state.loading=true;state.error=false;render();try{const response=await fetch('/home-data.json',{cache:'no-cache'});if(!response.ok)throw new Error('Public data unavailable');const data=await response.json();if(!Array.isArray(data.videos))throw new Error('Public videos unavailable');const prepared=prepare(data);state.videos=prepared.videos;state.channels=prepared.channels;state.updated=data.collectedAt||data.generatedAt||data.updatedAt||data.fetchedAt||null;state.loaded=true;}catch{state.error=true;}finally{state.loading=false;render();}}
document.querySelectorAll('[data-preview-lang]').forEach(button=>button.addEventListener('click',()=>{state.lang=button.dataset.previewLang;try{localStorage.setItem('radar.lang',state.lang);}catch{}render();}));
document.querySelectorAll('[data-preview-region]').forEach(button=>button.addEventListener('click',()=>{state.region=button.dataset.previewRegion;state.limit=24;render();}));
document.querySelectorAll('[data-preview-view]').forEach(button=>button.addEventListener('click',()=>{state.view=button.dataset.previewView;state.limit=24;render();if(state.view==='topics')$('previewSearch').focus({preventScroll:true});}));
$('previewSearch').addEventListener('input',event=>{state.search=event.target.value;state.limit=24;render();});$('previewSort').addEventListener('change',event=>{state.sort=event.target.value;state.limit=24;render();});$('previewMore').addEventListener('click',()=>{state.limit+=24;render();});$('previewRefresh').addEventListener('click',load);
load();
