// Read-only Studio snapshots and public references. No authentication or database writes.
const REALTIME_SOURCE = '/home-data.json';
const COPY = {
  ko:{skip:'본문으로 이동',workspace:'내 채널 관리',menu:'대시보드 메뉴',overview:'한눈에',references:'레퍼런스',topics:'소재 탐색',snapshot:'수집 스냅샷',home:'소개 페이지',language:'언어',eyebrow:'대시보드 미리보기 · 수집 스냅샷',title:'내 채널을 한눈에.',subtitle:'여러 운영 채널의 최근 48시간 실적을 한곳에서 확인하세요.',refresh:'다시 불러오기',summary:'운영 현황',views48:'최근 48시간 조회수',views60:'최근 60분 조회수',managedChannels:'운영 채널',allChannels:'전체 운영 채널',minuteNote:'실제 분 단위 수집값',managedNote:'하나의 대시보드에서 함께 확인',realtimeTitle:'조회수 · 최근 48시간',chartScope:'차트 범위',hourly:'1시간 단위',minuteTitle:'최근 60분 · 1분 단위',managedTitle:'모든 운영 채널',managedSubtitle:'채널별 48시간 실적과 시간별 흐름을 함께 보세요. 프로필은 익명 운영채널 아이콘입니다.',managedSearch:'운영 채널 검색',sort48:'48시간 조회수 높은 순',sortName:'채널 이름순',sort:'정렬',filters:'영상 필터',search:'영상·채널 검색',sortViews:'조회수 높은 순',sortNew:'최신순',totalViews:'수집 영상 누적 조회수',channelList:'참고할 채널',channelListNote:'공개 채널과 실제 영상에서 다음 소재를 찾아보세요.',videoTitle:'지금 살펴볼 영상',topicTitle:'다음 소재를 찾아보세요.',topicSubtitle:'영상 제목과 채널 이름으로 레퍼런스를 검색하세요.',topicVideos:'소재로 참고할 영상',more:'영상 더 보기',loading:'운영 채널 수집 데이터를 불러오는 중이에요…',failed:'운영 채널 데이터를 불러오지 못했어요. 다시 불러오기를 눌러 주세요.',referenceLoading:'공개 영상 데이터를 불러오는 중이에요…',referenceFailed:'공개 영상 데이터를 불러오지 못했어요. 다시 불러오기를 눌러 주세요.',empty:'조건에 맞는 항목이 없어요.',unknown:'미확인',notCollected:'수집값 없음',viewUnit:'회',items:'개 영상',channelUnit:'개 채널',videoCount:'개 영상',updated:'수집 시각',referenceUpdated:'자료 확인',thumb:'YouTube 영상',dateUnknown:'게시일 미확인',snapshotFooter:'YouTube Studio에서 수집한 시점의 실적입니다. 새로 불러오기는 저장된 스냅샷을 확인합니다.',referenceFooter:'공개 영상 레퍼런스입니다. 다른 채널의 CNOL RADAR 이용 후기나 추천을 의미하지 않습니다.',coverage:'확인된 수집값만 합산 · 누락된 값은 미확인',verified:'확인',hoursAgo:'48시간 전',minutesAgo:'60분 전',captured:'수집 기준',seriesUnknown:'시간별 수집값이 없습니다.',partial:'일부 채널 수집값',channel48:'48시간',channel60:'60분',referenceCounts:'영상 / 채널',barLabel:'조회수',observed:'확인된 버킷'},
  en:{skip:'Skip to content',workspace:'MY CHANNELS',menu:'Dashboard menu',overview:'Overview',references:'References',topics:'Find ideas',snapshot:'Collected snapshot',home:'About CNOL RADAR',language:'Language',eyebrow:'Dashboard preview · Collected snapshot',title:'All your channels, together.',subtitle:'See the last 48 hours across your managed channels in one place.',refresh:'Reload data',summary:'Channel performance',views48:'Views · last 48 hours',views60:'Views · last 60 minutes',managedChannels:'Managed channels',allChannels:'All managed channels',minuteNote:'Collected minute-by-minute figures',managedNote:'Together in one dashboard',realtimeTitle:'Views · last 48 hours',chartScope:'Chart scope',hourly:'Hourly',minuteTitle:'Last 60 minutes · per minute',managedTitle:'All managed channels',managedSubtitle:'Compare 48-hour performance and hourly activity. Profiles are anonymous channel icons.',managedSearch:'Search managed channels',sort48:'Most views in 48 hours',sortName:'Channel name',sort:'Sort',filters:'Video filters',search:'Search videos or channels',sortViews:'Most viewed',sortNew:'Newest first',totalViews:'Collected videos · total views',channelList:'Channels to explore',channelListNote:'Find your next idea in public channels and real videos.',videoTitle:'Videos to explore',topicTitle:'Find your next idea.',topicSubtitle:'Search reference videos by title or channel name.',topicVideos:'Videos for your next idea',more:'Show more videos',loading:'Loading collected channel data…',failed:'Channel data could not be loaded. Select Reload data to try again.',referenceLoading:'Loading public video data…',referenceFailed:'Public video data could not be loaded. Select Reload data to try again.',empty:'No items match.',unknown:'Unverified',notCollected:'No collected values',viewUnit:'views',items:'videos',channelUnit:'channels',videoCount:'videos',updated:'Captured',referenceUpdated:'Data checked',thumb:'YouTube video',dateUnknown:'Publication date unavailable',snapshotFooter:'Performance captured from YouTube Studio. Reload retrieves the saved snapshot.',referenceFooter:'Public reference videos. These are not testimonials or endorsements of CNOL RADAR by other channels.',coverage:'Only collected values are added up · missing values remain unverified',verified:'Verified',hoursAgo:'48 hours earlier',minutesAgo:'60 minutes earlier',captured:'Capture time',seriesUnknown:'Hourly values are unavailable.',partial:'Partial channel data',channel48:'48 hours',channel60:'60 minutes',referenceCounts:'videos / channels',barLabel:'Views',observed:'observed buckets'},
  ja:{skip:'本文へ移動',workspace:'マイチャンネル管理',menu:'ダッシュボードメニュー',overview:'ひと目で',references:'レファレンス',topics:'ネタ探し',snapshot:'収集スナップショット',home:'紹介ページ',language:'言語',eyebrow:'ダッシュボードプレビュー・収集スナップショット',title:'すべてのチャンネルを、ひと目で。',subtitle:'運営する複数チャンネルの直近48時間の実績を一か所で確認できます。',refresh:'再読み込み',summary:'運営状況',views48:'直近48時間の再生回数',views60:'直近60分の再生回数',managedChannels:'運営チャンネル',allChannels:'全運営チャンネル',minuteNote:'実際に収集した1分単位の数値',managedNote:'ひとつのダッシュボードで確認',realtimeTitle:'再生回数・直近48時間',chartScope:'チャート範囲',hourly:'1時間単位',minuteTitle:'直近60分・1分単位',managedTitle:'すべての運営チャンネル',managedSubtitle:'各チャンネルの48時間実績と時間別の推移を確認できます。プロフィールは匿名の運営チャンネルアイコンです。',managedSearch:'運営チャンネルを検索',sort48:'48時間の再生回数が多い順',sortName:'チャンネル名順',sort:'並び順',filters:'動画フィルター',search:'動画・チャンネルを検索',sortViews:'再生回数が多い順',sortNew:'新しい順',totalViews:'収集動画の累計再生回数',channelList:'参考にするチャンネル',channelListNote:'公開チャンネルと実際の動画から次のネタを探せます。',videoTitle:'チェックしたい動画',topicTitle:'次のネタを探しましょう。',topicSubtitle:'タイトルやチャンネル名で参考動画を検索できます。',topicVideos:'ネタの参考になる動画',more:'動画をもっと見る',loading:'運営チャンネルの収集データを読み込み中です…',failed:'チャンネルデータを読み込めませんでした。再読み込みを押してください。',referenceLoading:'公開動画データを読み込み中です…',referenceFailed:'公開動画データを読み込めませんでした。再読み込みを押してください。',empty:'条件に合う項目はありません。',unknown:'未確認',notCollected:'収集値なし',viewUnit:'回',items:'本の動画',channelUnit:'チャンネル',videoCount:'本の動画',updated:'収集時刻',referenceUpdated:'データ確認',thumb:'YouTube動画',dateUnknown:'公開日未確認',snapshotFooter:'YouTube Studioから収集した時点の実績です。再読み込みは保存済みスナップショットを取得します。',referenceFooter:'公開参考動画です。他のチャンネルによるCNOL RADARへの推薦やレビューを意味しません。',coverage:'確認できた収集値だけを合算・欠測値は未確認のまま表示',verified:'確認',hoursAgo:'48時間前',minutesAgo:'60分前',captured:'収集時点',seriesUnknown:'時間別の収集値はありません。',partial:'一部チャンネルの収集値',channel48:'48時間',channel60:'60分',referenceCounts:'動画 / チャンネル',barLabel:'再生回数',observed:'確認済み区間'}
};
const $=id=>document.getElementById(id);
const state={lang:'ko',view:'overview',scope:'all',managedSearch:'',managedSort:'views',search:'',sort:'views',limit:24,realtime:null,realtimeLoading:false,realtimeError:false,referencesLoaded:false,referenceLoading:false,referenceError:false,videos:[],channels:new Map(),referenceUpdated:null};
try{const value=localStorage.getItem('radar.lang');if(COPY[value])state.lang=value;}catch{}
const text=key=>(COPY[state.lang]||COPY.ko)[key];
const locale=()=>({ko:'ko-KR',en:'en-US',ja:'ja-JP'})[state.lang];
const num=value=>value==null?'—':Number(value).toLocaleString(locale());
const isCount=value=>typeof value==='number'&&Number.isFinite(value)&&value>=0;
const normal=value=>String(value||'').normalize('NFKC').toLowerCase();
const safeImage=value=>typeof value==='string'&&(value.startsWith('https://')||(value.startsWith('/')&&!value.startsWith('//')))?value:null;
const series=value=>Array.isArray(value)?value.map(point=>isCount(point)?point:null):[];
const knownSum=values=>{const known=values.filter(isCount);return known.length?known.reduce((sum,value)=>sum+value,0):null;};
function node(tag,className,content){const el=document.createElement(tag);if(className)el.className=className;if(content!=null)el.textContent=content;return el;}
function avatar(channel,size){const source=safeImage(channel?.thumbnail);if(source){const img=node('img','preview-avatar');img.src=source;img.alt='';img.loading='lazy';if(size){img.width=size;img.height=size;}return img;}return node('span','preview-avatar preview-avatar-fallback',channel?.index!=null?String(channel.index).padStart(2,'0'):String(channel?.name||'Y').slice(0,1));}
function managedAvatar(channel){const icon=node('span','preview-avatar preview-managed-avatar');const tile=((channel.index||1)-1)%30;icon.style.backgroundPosition=(tile%6*20)+'% '+(Math.floor(tile/6)*25)+'%';icon.setAttribute('aria-hidden','true');return icon;}
function dateLabel(value,short=false){const stamp=typeof value==='number'?value:Date.parse(value);return Number.isFinite(stamp)&&stamp>0?new Date(stamp).toLocaleString(locale(),short?{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}:{dateStyle:'medium',timeStyle:'short'}):text('unknown');}
function prepareRealtime(payload){
  const data=payload?.realtime;
  if(!data||!Array.isArray(data.channels))throw new Error('Channel snapshot unavailable');
  const channels=[],seen=new Set();
  for(const raw of data.channels){const id=String(raw?.id||'');if(!id||seen.has(id))continue;seen.add(id);const index=channels.length+1,hourly=series(raw.hourly48),minutes=series(raw.minuteBars60);channels.push({id,index,name:String(raw.displayName||('Channel '+String(index).padStart(2,'0'))),thumbnail:null,hourly,minutes,total48:isCount(raw.total48)?raw.total48:knownSum(hourly),total60:isCount(raw.minute60)?raw.minute60:knownSum(minutes)});}
  if(!channels.length)throw new Error('No managed channels');
  const capturedAt=data.capturedAt||null;
  return {channels,channelCount:isCount(data.channelCount)?data.channelCount:channels.length,total48:isCount(data.views48)?data.views48:knownSum(channels.map(channel=>channel.total48)),total60:isCount(data.views60)?data.views60:knownSum(channels.map(channel=>channel.total60)),bars48:series(data.bars48),bars60:series(data.bars60),capturedAt,hourly:{t0:null,stepMs:3600000,capturedAt},minute:{t0:null,stepMs:60000,capturedAt}};
}
function prepareReferences(data){const channels=new Map();for(const channel of Array.isArray(data.channels)?data.channels:[]){if(channel?.id)channels.set(String(channel.id),{id:String(channel.id),name:String(channel.name||''),thumbnail:channel.thumbnail});}const videos=[],seen=new Set();for(const video of Array.isArray(data.videos)?data.videos:[]){if(!video||!/^[A-Za-z0-9_-]{11}$/.test(video.id||'')||seen.has(video.id))continue;seen.add(video.id);const channelId=String(video.channelId||''),known=channels.get(channelId);if(!known&&channelId)channels.set(channelId,{id:channelId,name:String(video.channelName||''),thumbnail:null});videos.push({id:video.id,title:String(video.title||''),views:isCount(video.views)?video.views:null,format:video.format==='shorts'?'shorts':'long',channelId,channelName:String(video.channelName||known?.name||''),thumbnail:video.thumbnail,publishedAt:video.publishedAt||null});}return{videos,channels};}
function filtered(){const query=normal(state.search);return state.videos.filter(video=>!query||normal(video.title+' '+video.channelName).includes(query)).sort((a,b)=>state.sort==='new'?(Date.parse(b.publishedAt)||0)-(Date.parse(a.publishedAt)||0):(b.views??-1)-(a.views??-1));}
function aggregated(videos){const groups=new Map();for(const video of videos){if(!video.channelId)continue;if(!groups.has(video.channelId))groups.set(video.channelId,{channel:state.channels.get(video.channelId)||{id:video.channelId,name:video.channelName},views:null,count:0});const group=groups.get(video.channelId);group.count++;if(video.views!=null)group.views=(group.views??0)+video.views;}return[...groups.values()].sort((a,b)=>(b.views??-1)-(a.views??-1));}
function chartRows(channels,key,block){const length=Math.max(0,...channels.map(channel=>channel[key].length));return Array.from({length},(_,index)=>{const values=channels.map(channel=>channel[key][index]);const known=values.filter(isCount);return{views:knownSum(values),known:known.length,total:channels.length,at:block.t0==null?null:block.t0+index*block.stepMs};});}
function renderBars(id,labelsId,rows,minute=false){const root=$(id),ticks=$(labelsId);root.replaceChildren();ticks.replaceChildren();if(!rows.length){root.append(node('div','preview-empty',state.realtimeLoading?text('loading'):text('seriesUnknown')));return;}const max=Math.max(1,...rows.map(row=>row.views??0));const bars=node('div','preview-time-bars');bars.setAttribute('role','list');for(const row of rows){const bar=node('div','preview-time-bar'+(row.views==null?' is-missing':''));bar.setAttribute('role','listitem');bar.tabIndex=0;if(row.views!=null)bar.style.height=(row.views/max*100)+'%';const label=(row.at==null?(bars.children.length+1)+'/'+rows.length+' '+text(minute?'minuteTitle':'hourly'):dateLabel(row.at,true))+' · '+num(row.views)+' '+text('viewUnit')+' · '+row.known+'/'+row.total+' '+text('channelUnit');bar.title=label;bar.setAttribute('aria-label',label);bars.append(bar);}root.append(bars);ticks.append(node('span','',rows[0].at==null?text(minute?'minutesAgo':'hoursAgo'):dateLabel(rows[0].at,true)),node('span','',rows.at(-1).at==null?text('captured'):dateLabel(rows.at(-1).at,true)));}
function renderSparkline(root,values){if(!values.length){root.append(node('div','preview-sparkline-empty',text('seriesUnknown')));return;}const spark=node('div','preview-sparkline');spark.setAttribute('aria-label',text('views48'));const max=Math.max(1,...values.map(value=>value??0));for(const value of values){const bar=node('span',value==null?'is-missing':'');if(value!=null)bar.style.height=(value/max*100)+'%';bar.title=value==null?text('unknown'):num(value)+' '+text('viewUnit');spark.append(bar);}root.append(spark);}
function renderManaged(channels){const root=$('previewManagedGrid');root.replaceChildren();const query=normal(state.managedSearch);const visible=channels.filter(channel=>!query||normal(channel.name).includes(query)).sort((a,b)=>state.managedSort==='name'?a.name.localeCompare(b.name,locale()):(b.total48??-1)-(a.total48??-1));$('previewManagedResult').textContent=num(visible.length)+' '+text('channelUnit');for(const channel of visible){const card=node('article','preview-managed-card'),head=node('div','preview-managed-head'),name=node('div','preview-managed-name');name.append(node('h3','',channel.name),node('small','',text('channel48')));head.append(managedAvatar(channel),name);const value=node('div','preview-managed-value');value.append(node('strong','',num(channel.total48)),node('span','',text('channel60')+' '+num(channel.total60)));card.append(head,value);renderSparkline(card,channel.hourly);const known=channel.hourly.filter(isCount).length;card.append(node('p','preview-managed-caption',known+'/'+channel.hourly.length+' '+text('observed')));root.append(card);}if(!visible.length)root.append(node('div','preview-empty',state.realtimeLoading?text('loading'):text('empty')));}
function renderRealtime(){
  const data=state.realtime,channels=data?.channels||[];
  $('previewTotal48').textContent=num(data?.total48);$('previewTotal60').textContent=num(data?.total60);$('previewManagedCount').textContent=data?num(data.channelCount):'—';
  const known48=channels.filter(channel=>channel.total48!=null).length,known60=channels.filter(channel=>channel.total60!=null).length;
  $('preview48Note').textContent=text('allChannels')+(known48<channels.length?' · '+known48+'/'+channels.length+' '+text('verified'):'');
  $('preview60Note').textContent=data?.total60!=null?text('minuteNote')+(known60<channels.length?' · '+known60+'/'+channels.length+' '+text('verified'):''):text('notCollected');
  const selector=$('previewScope');selector.replaceChildren();const all=node('option','',text('allChannels'));all.value='all';selector.append(all);
  for(const channel of channels){const option=node('option','',channel.name);option.value=channel.id;selector.append(option);}
  if(state.scope!=='all'&&!channels.some(channel=>channel.id===state.scope))state.scope='all';selector.value=state.scope;
  const active=state.scope==='all'?channels:channels.filter(channel=>channel.id===state.scope);
  const fromBars=values=>values.map(value=>({views:value,known:value==null?0:data.channelCount,total:data.channelCount,at:null}));
  const hourly=state.scope==='all'&&data?.bars48.length?fromBars(data.bars48):chartRows(active,'hourly',data?.hourly||{t0:null,stepMs:3600000});
  const minutes=state.scope==='all'&&data?.bars60.length?fromBars(data.bars60):chartRows(active,'minutes',data?.minute||{t0:null,stepMs:60000});
  renderBars('previewHourlyChart','previewHourlyLabels',hourly);renderBars('previewMinuteChart','previewMinuteLabels',minutes,true);
  $('previewMinutePanel').hidden=!minutes.length;$('previewChart48Total').textContent=num(knownSum(hourly.map(row=>row.views)));$('previewChart60Total').textContent=num(knownSum(minutes.map(row=>row.views)));
  $('previewRealtimeStamp').textContent=data?.capturedAt?text('updated')+' '+dateLabel(data.capturedAt):text('notCollected');$('previewMinuteStamp').textContent=data?.capturedAt?text('updated')+' '+dateLabel(data.capturedAt):'';
  $('previewCoverage').textContent=text('coverage');renderManaged(channels);
}
function renderChannels(groups){const root=$('previewChannelGrid');root.replaceChildren();for(const group of groups){const card=node('article','preview-channel-card'),body=node('div');body.append(node('h3','',group.channel.name),node('p','',num(group.count)+' '+text('videoCount')+' · '+num(group.views)+' '+text('viewUnit')));card.append(avatar(group.channel,42),body);root.append(card);}if(!groups.length)root.append(node('div','preview-empty',text('empty')));}
function renderVideos(videos){const root=$('previewVideoGrid');root.replaceChildren();for(const video of videos.slice(0,state.limit)){const card=node('article','preview-video-card'),button=node('button','preview-thumbnail creator-video');button.type='button';button.dataset.video=video.id;button.dataset.title=video.title;button.dataset.channel=video.channelName;button.dataset.format=video.format;button.setAttribute('aria-label',video.title||text('thumb'));const source=safeImage(video.thumbnail);if(source){const image=node('img');image.src=source;image.alt='';image.loading='lazy';image.width=480;image.height=270;button.append(image);}else button.append(node('span','preview-thumbnail-fallback',text('thumb')));button.append(node('span','preview-play','▶'),node('span','preview-format',video.format==='shorts'?'SHORTS':'VIDEO'));const body=node('div','preview-video-body');body.append(node('h3','',video.title));const author=node('div','preview-video-author');author.append(avatar(state.channels.get(video.channelId)),node('span','',video.channelName));const metadata=node('div','preview-video-meta'),date=Date.parse(video.publishedAt);metadata.append(node('span','preview-video-views',num(video.views)+' '+text('viewUnit')),node('span','',Number.isFinite(date)?new Date(date).toLocaleDateString(locale(),{year:'numeric',month:'short',day:'numeric'}):text('dateUnknown')));body.append(author,metadata);card.append(button,body);root.append(card);}if(!videos.length)root.append(node('div','preview-empty',state.referenceLoading?text('referenceLoading'):state.referenceError?text('referenceFailed'):text('empty')));$('previewMore').hidden=videos.length<=state.limit;$('previewResultCount').textContent=num(videos.length)+' '+text('items');}
function setLabels(){document.documentElement.lang=state.lang;document.title='CNOL RADAR · '+text('overview');document.querySelectorAll('[data-preview-label]').forEach(el=>{el.textContent=text(el.dataset.previewLabel);});document.querySelectorAll('[data-preview-aria]').forEach(el=>el.setAttribute('aria-label',text(el.dataset.previewAria)));document.querySelectorAll('[data-preview-placeholder]').forEach(el=>el.placeholder=text(el.dataset.previewPlaceholder));document.querySelectorAll('[data-preview-lang]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.previewLang===state.lang)));}
function render(){setLabels();const overview=state.view==='overview';$('previewOverview').hidden=!overview;$('previewReferences').hidden=overview;$('previewChannelsSection').hidden=state.view==='topics';$('previewTitle').textContent=state.view==='topics'?text('topicTitle'):state.view==='references'?text('channelList'):text('title');$('previewSubtitle').textContent=state.view==='topics'?text('topicSubtitle'):state.view==='references'?text('channelListNote'):text('subtitle');$('previewBreadcrumb').textContent=text(state.view);$('previewVideoTitle').textContent=state.view==='topics'?text('topicVideos'):text('videoTitle');document.querySelectorAll('[data-preview-view]').forEach(el=>{if(el.dataset.previewView===state.view)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current');});const loading=overview?state.realtimeLoading:state.referenceLoading,error=overview?state.realtimeError:state.referenceError;$('previewRefresh').disabled=loading;$('previewStatus').classList.toggle('is-error',error);$('previewStatus').textContent=loading?text(overview?'loading':'referenceLoading'):error?text(overview?'failed':'referenceFailed'):overview?(state.realtime?num(state.realtime.channels.length)+' '+text('channelUnit')+' · '+text('snapshot'):''):num(state.videos.length)+' '+text('items');$('previewFooter').textContent=text(overview?'snapshotFooter':'referenceFooter');const stamp=overview?state.realtime?.capturedAt:state.referenceUpdated;$('previewUpdated').textContent=stamp?text(overview?'updated':'referenceUpdated')+' '+dateLabel(stamp):'';if(overview)renderRealtime();else{const videos=filtered(),groups=aggregated(videos);$('previewTotalViews').textContent=num(knownSum(videos.map(video=>video.views)));$('previewReferenceCounts').textContent=num(videos.length)+' '+text('items')+' · '+num(groups.length)+' '+text('channelUnit');renderChannels(groups);renderVideos(videos);}}
async function loadRealtime(){if(state.realtimeLoading)return;state.realtimeLoading=true;state.realtimeError=false;render();try{const response=await fetch(REALTIME_SOURCE,{cache:'no-cache'});if(!response.ok)throw new Error('Channel snapshot unavailable');const data=await response.json();state.realtime=prepareRealtime(data);const prepared=prepareReferences(data);state.videos=prepared.videos;state.channels=prepared.channels;state.referenceUpdated=data.collectedAt||data.generatedAt||data.updatedAt||data.fetchedAt||null;state.referencesLoaded=Array.isArray(data.videos);}catch{state.realtimeError=true;}finally{state.realtimeLoading=false;render();}}
async function loadReferences(){if(state.referenceLoading)return;state.referenceLoading=true;state.referenceError=false;render();try{const response=await fetch('/home-data.json',{cache:'no-cache'});if(!response.ok)throw new Error('Public videos unavailable');const data=await response.json();if(!Array.isArray(data.videos))throw new Error('Public videos unavailable');const prepared=prepareReferences(data);state.videos=prepared.videos;state.channels=prepared.channels;state.referenceUpdated=data.collectedAt||data.generatedAt||data.updatedAt||data.fetchedAt||null;state.referencesLoaded=true;}catch{state.referenceError=true;}finally{state.referenceLoading=false;render();}}
document.querySelectorAll('[data-preview-lang]').forEach(button=>button.addEventListener('click',()=>{state.lang=button.dataset.previewLang;try{localStorage.setItem('radar.lang',state.lang);}catch{}render();}));
document.querySelectorAll('[data-preview-view]').forEach(button=>button.addEventListener('click',()=>{state.view=button.dataset.previewView;state.limit=24;render();if(state.view!=='overview'&&!state.referencesLoaded)loadReferences();if(state.view==='topics')$('previewSearch').focus({preventScroll:true});}));
$('previewScope').addEventListener('change',event=>{state.scope=event.target.value;render();});
$('previewManagedSearch').addEventListener('input',event=>{state.managedSearch=event.target.value;render();});$('previewManagedSort').addEventListener('change',event=>{state.managedSort=event.target.value;render();});
$('previewSearch').addEventListener('input',event=>{state.search=event.target.value;state.limit=24;render();});$('previewSort').addEventListener('change',event=>{state.sort=event.target.value;state.limit=24;render();});$('previewMore').addEventListener('click',()=>{state.limit+=24;render();});$('previewRefresh').addEventListener('click',()=>state.view==='overview'?loadRealtime():loadReferences());
loadRealtime();
